import {useEffect,useMemo,useState} from 'react';
import type {PlayerView, SpectatorView} from '@gst/rules';
import type {ReplayData,RoomDetail} from '@gst/protocol';
import {net} from './net.js';
import {CharacterCard,artOf} from './art.js';
export function Results({view,room}:{view:PlayerView|SpectatorView;room:RoomDetail}) {
 const [replay,setReplay]=useState<ReplayData|null>(null);const [cursor,setCursor]=useState(0);const [playing,setPlaying]=useState(false);const [speed,setSpeed]=useState(1);const [filter,setFilter]=useState('all');const [logPage,setLogPage]=useState(0);
 useEffect(()=>{const off=net.on(m=>{if(m.type==='replay'){setReplay(m.replay);setCursor(m.replay.frames.at(-1)?.at??0);}});net.send({type:'replay.get'});return off;},[room.id]);
 useEffect(()=>setLogPage(0),[filter,cursor]);
 const end=replay?.frames.at(-1)?.at??0;
 useEffect(()=>{if(!playing)return;const t=setInterval(()=>setCursor(t=>{if(t+250*speed>=end){setPlaying(false);return end;}return t+250*speed;}),250);return()=>clearInterval(t);},[playing,speed,end]);
 const frame=useMemo(()=>replay?.frames.slice().reverse().find(f=>f.at<=cursor)?.view??replay?.frames[0]?.view,[replay,cursor]);
 const visibleEvents=(replay?.events??[]).filter(e=>e.at<=cursor&&(filter==='all'||(filter==='attack'?/attack|death/.test(e.kind):/skill|inspect|scan|gem/.test(e.kind))));
 const isPlayer=!('spectator' in view);const won=isPlayer&&view.me.side===view.winner;const faction=isPlayer?artOf(view.me.character).faction:'P1';
 const fmt=(n:number)=>`${Math.floor(n/60000)}:${String(Math.floor(n/1000)%60).padStart(2,'0')}`;
 return <div className={`game-board mode-${room.mode}`}><div className="replay-shell"><header className="row spread"><b>{view.modeName} · 전투 기록</b><button className="ghost" onClick={()=>net.send({type:'room.leave'})}>대기실로</button></header><section className={`result-heading ${won?'win':'loss'}`}><img className="result-art" src={`${import.meta.env.BASE_URL}ui/result-${faction}-${won?'win':'loss'}.webp`} alt="" onError={e=>{e.currentTarget.style.display='none';}}/><span className="eyebrow">THE CHRONICLE</span><h1>{isPlayer?(won?'승리':'패배'):'전투 종료'}</h1><p>{view.winner?view.sideNames[view.winner]:''} · {view.endReason}</p><div className="result-summary"><span>총 전투 시간 {fmt(view.elapsedMs)}</span><span>종료 턴 {view.turn}</span></div></section><section className="hall-panel"><h2>전장의 복기</h2><p className="muted">전체 정체를 공개한 상태로 기록을 재생합니다. 카드는 저장된 시점의 마나·생존 상태를 표시합니다.</p>{!replay?<p>기록을 불러오는 중…</p>:<><div className="replay-controls"><button onClick={()=>{if(cursor>=end)setCursor(0);setPlaying(!playing);}}>{playing?'일시 정지':'재생'}</button><button className="ghost" onClick={()=>{setCursor(0);setPlaying(false);}}>처음</button><input aria-label="복기 시간" type="range" min={0} max={end} step={100} value={cursor} onChange={e=>setCursor(Number(e.target.value))}/><span>{fmt(cursor)} / {fmt(end)}</span><select aria-label="재생 속도" value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[1,2,4,8,16].map(n=><option key={n} value={n}>{n}배속</option>)}</select></div><div className="replay-roster">{frame?.players.map(p=><div key={p.id}><CharacterCard character={p.character} name={p.characterName} title={frame.roster.find(c=>c.key===p.character)?.title} dead={!p.alive}/><b>[{p.seat}] {p.nickname}</b><p className="small">마나 {p.mana} · 추가 목숨 {p.extraLives} · {p.alive?'생존':'사망'}</p></div>)}</div><div className="row spread"><h3>전체 행동 로그</h3><select aria-label="로그 종류" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">전체 행동</option><option value="attack">공격·사망</option><option value="skill">스킬</option></select></div><div className="row spread"><button className="ghost" disabled={(logPage+1)*200>=visibleEvents.length} onClick={()=>setLogPage(p=>p+1)}>이전 기록</button><span>{visibleEvents.length}개 기록 · {logPage+1}페이지</span><button className="ghost" disabled={logPage===0} onClick={()=>setLogPage(p=>p-1)}>다음 기록</button></div><div className="replay-events" role="log">{visibleEvents.slice(Math.max(0,visibleEvents.length-(logPage+1)*200),Math.max(0,visibleEvents.length-logPage*200)).map(e=><div className="replay-event" key={e.seq}><span className="muted">{fmt(e.at)} · </span>{e.vis.to!=='all'&&<span className="tag">비공개 기록</span>} {e.text}</div>)}</div></>}</section></div></div>;
}
